### ISSUE TITLE
Docs for initial setup?

### ISSUE THREAD

**Issue by labithiotis** [lasuillard/raindrop-sync-chrome#53]
@lasuillard  It would be handy to include some basic docs for the setup process. 

I assume we need to create an application in Raindrop to acquire a Client Id, Client Secrete and a Token. 

However, it's not clear what the redirect URI should be for the application. I tried localhost and https://<extensionid>.chromiumapp.org but all changes resulted in `Error: Request failed with error: Incorrect redirect_uri` when registering in the extension for syncing.

**Comment by lasuillard** [comment]
Thank you for your interest on this project. I could now can afford some time for this project recently, I definitely take consideration of your suggestion.

Until I update the documentation, you could check below image (my test app configuration) for a quick reference:

![image](https://github.com/user-attachments/assets/16ca96c6-7e66-4278-b1e2-4f0fae7798ed)

The Chrome extension ID (`https://<EXTENSION_ID>.chromiumapp.org`) may differ based on extension's source directory, as it's how it is generated.

Or, you could just copy and paste the Test token to Access Token field directly, without having to go through OAuth authorization step.

**Comment by labithiotis** [comment]
@lasuillard Thanks for the rapid response, this is exactly what I did but when you click register within the extension options and you get the auth popup and complete the flow I get an error about the redirect url being invalid. 

Oh the issue was I was missing a forward slash, so url needs to be `https://<EXTENSION_ID>.chromiumapp.org/` **not** `https://<EXTENSION_ID>.chromiumapp.org`

Also seems like syncing is not working as I expected, it generates all new bookmarks in another folder each time I click sync.

![image](https://github.com/user-attachments/assets/c2be4b33-de19-4543-bcc3-d07230f425c4)

**Comment by lasuillard** [comment]
Well, in fact, this project is at an early stage, and I made the sync work like that for testing purposes only, not to break any existing bookmarks due to poor implementation.

I will keep trying to make improvements, but for now, it's not ready for practical use. 🥲

**Comment by labithiotis** [comment]
@lasuillard That's cool and I understand, I assumed with 11 stars this project was a little more "complete". I will have a look at https://github.com/lasuillard/raindrop-sync-chrome/blob/main/src/lib/chrome/bookmark.ts#L9 in my spare time to see if we can enhance that logic to actually "sync"
